### ISSUE TITLE
i18n: Remove URL from translation

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/integration_documenso#4] opened 2024-11-15 16:52 UTC
The URL should not be translatable:

https://github.com/nextcloud/integration_documenso/blob/035b74e7fc5c78f9117813bf6269bdce485d9ffb/src/components/PersonalSettings.vue#L20

Reported at Transifex.

**Comment by janepie** [comment] 2024-11-18 12:26
Duplicate of #2 but thank you for spotting this!

**Closed** 2024-11-19 08:16 UTC
